version: '3.8'
services:
  stats-server:
    build:
      context: ./stats-service/server
      dockerfile: Dockerfile
    image: stats-image
    container_name: stats-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - spring.datasource.url=jdbc:postgresql://stats-db:5432/stats
      - spring.datasource.user=root
      - spring.datasource.password=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    image: main-image
    container_name: main-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - spring.datasource.url=jdbc:postgresql://ewm-db:5432/main
      - spring.datasource.user=root
      - spring.datasource.password=root
      - stats-service.url=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "6542:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root